// Publer schedule + publisher/analytics workers.
// - Time base: America/Los_Angeles (PT). Slot grid = 08:00, 10:00, 12:00, 14:00,
//   16:00, 18:00, 20:00, 22:00 by default (configurable per-day via publer_config).
// - Publisher cron (every 5min): for each slot, if the current PT time is >=
//   slot_time AND we haven't published slot_index today, publish next pending.
//   This automatically backfills earlier slots when we first start mid-day.
// - Analytics poller: snapshot per publer_post_id every 30min for first 7 days,
//   then hourly through 30 days, then freeze.

import type { SupabaseClient } from "@supabase/supabase-js";
import {
  listAccounts,
  listPosts,
  postInsights,
  publishNow,
  uploadFromUrl,
  waitForJob,
} from "./publer.js";

const BUCKET = "reels";

// -------- Caption harvester --------
// Mines historical captions from Publer's post_insights for a given phone_slot,
// extracts unique hooks + hashtag frequencies, and upserts the template.
export async function harvestCaptions(
  sb: SupabaseClient,
  phoneSlot: string,
): Promise<{ posts_scanned: number; unique_hooks: number; unique_hashtags: number; template: any }> {
  const cfg = await loadConfig(sb);
  const { data: slot } = await sb
    .from("publer_slot_config")
    .select("phone_slot, publer_account_id")
    .eq("phone_slot", phoneSlot)
    .maybeSingle();
  if (!slot) throw new Error(`no slot for ${phoneSlot}`);

  // Pull last 120 days of posts
  const now = new Date();
  const to = ptNow(now).ymd;
  const from = ptNow(new Date(now.getTime() - 120 * 86400_000)).ymd;

  const captions: string[] = [];
  for (let page = 0; page < 20; page++) {
    const resp = await postInsights(cfg.workspaceId, slot.publer_account_id, from, to, {
      page,
      sortBy: "scheduled_at",
      sortType: "DESC",
    });
    const posts = resp?.posts ?? [];
    if (!posts.length) break;
    for (const p of posts) if (p.text) captions.push(p.text);
    if (posts.length < 10) break;
  }

  // Extract hooks (text before first hashtag) and hashtag frequency
  const hookSet = new Set<string>();
  const tagFreq: Record<string, number> = {};
  for (const cap of captions) {
    const hashIdx = cap.indexOf("#");
    const hook = (hashIdx >= 0 ? cap.slice(0, hashIdx) : cap).trim();
    if (hook.length >= 2 && hook.length <= 120) hookSet.add(hook);
    const tags = (cap.match(/#[a-z0-9_]+/gi) || []).map((t) => t.slice(1).toLowerCase());
    for (const t of new Set(tags)) tagFreq[t] = (tagFreq[t] || 0) + 1;
  }

  const hooks = [...hookSet];
  // Top hashtags by frequency, keep top 30
  const sortedTags = Object.entries(tagFreq).sort((a, b) => b[1] - a[1]).slice(0, 30).map(([t]) => t);

  // Upsert template (preserve existing values if we found nothing new)
  const { data: existing } = await sb
    .from("device_content_templates")
    .select("*")
    .eq("phone_slot", phoneSlot)
    .maybeSingle();

  const mergedHooks = hooks.length ? Array.from(new Set([...(existing?.caption_hooks || []), ...hooks])) : (existing?.caption_hooks || []);
  const mergedTags = sortedTags.length ? Array.from(new Set([...(existing?.hashtag_pool || []), ...sortedTags])) : (existing?.hashtag_pool || []);

  const { data: tpl, error } = await sb
    .from("device_content_templates")
    .upsert({
      phone_slot: phoneSlot,
      caption_hooks: mergedHooks,
      hashtag_pool: mergedTags,
      hashtag_count_per_post: existing?.hashtag_count_per_post ?? 4,
      enabled: existing?.enabled ?? true,
      updated_at: new Date().toISOString(),
    }, { onConflict: "phone_slot" })
    .select()
    .single();
  if (error) throw error;

  return {
    posts_scanned: captions.length,
    unique_hooks: hooks.length,
    unique_hashtags: sortedTags.length,
    template: tpl,
  };
}

// -------- Caption composer --------
// Priority order (auto-use pending mode):
//   1. ACCEPTED queue_suggestions row (user-approved override)
//   2. PENDING queue_suggestions row (auto-generated by nightly cron, unreviewed)
//   3. device_content_templates hook + hashtag pool (legacy behavior)
//   4. Empty (previous fallback, logs miss)
// REJECTED suggestions are skipped so the template takes over.
// Hashtag selection avoids reusing the same set from the previous post to reduce
// IG/TikTok "same hashtag spam" flags.
async function composeCaption(
  sb: SupabaseClient,
  phoneSlot: string,
  queueRowId?: string,
): Promise<{ caption: string; hashtags: string[]; source: "accepted" | "pending" | "template" | "empty" }> {
  if (queueRowId) {
    const { data: sug } = await sb
      .from("queue_suggestions")
      .select("suggested_caption, suggested_hashtags, user_action, final_caption, final_hashtags")
      .eq("queue_id", queueRowId)
      .in("user_action", ["accepted", "pending"])
      .order("user_action", { ascending: true })  // 'accepted' sorts before 'pending' alphabetically
      .limit(1)
      .maybeSingle();
    if (sug) {
      const isAccepted = sug.user_action === "accepted";
      const caption = (isAccepted && sug.final_caption && sug.final_caption.trim())
        ? sug.final_caption
        : sug.suggested_caption;
      const rawTags = (isAccepted && sug.final_hashtags && sug.final_hashtags.length)
        ? sug.final_hashtags
        : (sug.suggested_hashtags || []);
      const hashtags = rawTags.map((t: string) => t.replace(/^#/, ""));
      console.log(`[caption] using ${sug.user_action} suggestion for queue`, queueRowId);
      return { caption, hashtags, source: isAccepted ? "accepted" : "pending" };
    }
  }

  const { data: tpl } = await sb
    .from("device_content_templates")
    .select("caption_hooks, hashtag_pool, hashtag_count_per_post, enabled")
    .eq("phone_slot", phoneSlot)
    .maybeSingle();

  if (!tpl || !tpl.enabled || !(tpl.caption_hooks?.length)) {
    console.log("[caption] no active template for", phoneSlot);
    return { caption: "", hashtags: [], source: "empty" };
  }

  // Pull the last N caption+hashtag sets we used on this slot so we can rotate
  const { data: recent } = await sb
    .from("publer_publish_log")
    .select("caption_used, hashtags_used")
    .eq("phone_slot", phoneSlot)
    .not("caption_used", "is", null)
    .order("attempted_at", { ascending: false })
    .limit(5);
  const recentHooks = new Set((recent ?? []).map((r: any) => (r.caption_used || "").split(/\s+#/)[0].trim()));
  const recentTagSets = (recent ?? []).map((r: any) => new Set<string>(r.hashtags_used ?? []));

  // Pick a hook not used in last 5 posts if possible
  const hooks: string[] = tpl.caption_hooks;
  const freshHooks = hooks.filter((h) => !recentHooks.has(h.trim()));
  const hookPool = freshHooks.length ? freshHooks : hooks;
  const hook = hookPool[Math.floor(Math.random() * hookPool.length)];

  // Pick N hashtags with least recent overlap
  const pool: string[] = (tpl.hashtag_pool || []).map((t: string) => t.replace(/^#/, ""));
  const want = Math.max(1, Math.min(tpl.hashtag_count_per_post || 4, pool.length));
  // Score each tag by how many of the last 5 posts it appeared in (lower = better)
  const scored = pool.map((tag) => ({ tag, score: recentTagSets.filter((s) => s.has(tag)).length + Math.random() * 0.1 }));
  scored.sort((a, b) => a.score - b.score);
  const chosen = scored.slice(0, want).map((s) => s.tag);

  const hashPart = chosen.map((t) => `#${t}`).join(" ");
  const caption = hashPart ? `${hook} ${hashPart}` : hook;
  return { caption, hashtags: chosen, source: "template" };
}


// Publer serializes media-from-url per workspace: parallel uploads get 403.
// A single in-process mutex is enough (single node instance).
let uploadMutex: Promise<void> = Promise.resolve();
async function withUploadLock<T>(fn: () => Promise<T>): Promise<T> {
  let release!: () => void;
  const gate = new Promise<void>((r) => (release = r));
  const prev = uploadMutex;
  uploadMutex = gate;
  await prev;
  try {
    return await fn();
  } finally {
    release();
  }
}

// --- PT time helpers ---------------------------------------------------------

/**
 * Returns { ymd: "2026-09-06", hhmm: "13:04", minutesSinceMidnight: 784 } in
 * America/Los_Angeles for the given date (default: now).
 */
export function ptNow(now: Date = new Date()): {
  ymd: string;
  hhmm: string;
  minutes: number;
  iso: string;
} {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/Los_Angeles",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).formatToParts(now);
  const get = (t: string) => parts.find((p) => p.type === t)?.value ?? "00";
  const ymd = `${get("year")}-${get("month")}-${get("day")}`;
  const hh = get("hour");
  const mm = get("minute");
  const minutes = parseInt(hh, 10) * 60 + parseInt(mm, 10);
  return { ymd, hhmm: `${hh}:${mm}`, minutes, iso: now.toISOString() };
}

/**
 * Convert "YYYY-MM-DD" + "HH:MM" (interpreted in America/Los_Angeles) to a UTC Date.
 * DST-safe: iterates once to correct offset.
 */
export function ptDateTimeToUtc(ymd: string, hhmm: string): Date {
  const [y, m, d] = ymd.split("-").map((n) => parseInt(n, 10));
  const [hh, mm] = hhmm.split(":").map((n) => parseInt(n, 10));
  // First naive guess: treat as UTC, then compute PT offset for that instant.
  let guess = Date.UTC(y, m - 1, d, hh, mm, 0);
  for (let i = 0; i < 2; i++) {
    const fmt = new Intl.DateTimeFormat("en-US", {
      timeZone: "America/Los_Angeles",
      timeZoneName: "shortOffset",
    }).formatToParts(new Date(guess));
    const off = fmt.find((p) => p.type === "timeZoneName")?.value ?? "GMT-8";
    // "GMT-7" or "GMT-08:00"
    const match = /GMT([+-])(\d{1,2})(?::?(\d{2}))?/.exec(off);
    if (!match) break;
    const sign = match[1] === "-" ? -1 : 1;
    const h = parseInt(match[2], 10);
    const min = match[3] ? parseInt(match[3], 10) : 0;
    const offsetMinutes = sign * (h * 60 + min);
    // If PT was interpreted as "PT time = UTC + offset", then UTC = PT - offset.
    const corrected = Date.UTC(y, m - 1, d, hh, mm, 0) - offsetMinutes * 60_000;
    guess = corrected;
  }
  return new Date(guess);
}

// --- Config helpers ----------------------------------------------------------

export interface Config {
  workspaceId: string;
  timezone: string;
  slotTimes: string[];      // "HH:MM"
  jitterMinutes: number;
}
export interface SlotConfig {
  phone_slot: string;
  publer_account_id: string;
  provider: "instagram" | "tiktok";
  handle: string;
  daily_target: number;
  paused: boolean;
  owner_user_id: string | null;
}

export async function loadConfig(sb: SupabaseClient): Promise<Config> {
  const { data, error } = await sb.from("publer_config").select("*").eq("id", "main").single();
  if (error) throw error;
  return {
    workspaceId: data.workspace_id,
    timezone: data.timezone,
    slotTimes: data.slot_times as string[],
    jitterMinutes: data.jitter_minutes as number,
  };
}

export async function loadSlots(sb: SupabaseClient): Promise<SlotConfig[]> {
  const { data, error } = await sb
    .from("publer_slot_config")
    .select("*")
    .order("phone_slot", { ascending: true });
  if (error) throw error;
  return data as SlotConfig[];
}

// --- Publisher ---------------------------------------------------------------

/**
 * Compute the set of slot_indexes that are eligible to publish RIGHT NOW for a
 * given LA day. Only indexes < daily_target are considered. An index is eligible
 * if PT-now-minutes >= slot_minutes.
 */
export function eligibleSlotIndexes(
  slotTimesHHMM: string[],
  dailyTarget: number,
  ptMinutesNow: number,
): number[] {
  const out: number[] = [];
  const limit = Math.min(dailyTarget, slotTimesHHMM.length);
  for (let i = 0; i < limit; i++) {
    const [h, m] = slotTimesHHMM[i].split(":").map((n) => parseInt(n, 10));
    if (h * 60 + m <= ptMinutesNow) out.push(i);
  }
  return out;
}

/** Get already-taken slot indexes today for a phone slot. */
async function takenSlotIndexes(
  sb: SupabaseClient,
  phone_slot: string,
  ymd: string,
): Promise<Set<number>> {
  const { data, error } = await sb
    .from("publer_publish_log")
    .select("slot_index,status")
    .eq("phone_slot", phone_slot)
    .eq("slot_local_date", ymd)
    .in("status", ["pending", "published"]);
  if (error) throw error;
  return new Set((data ?? []).map((r: any) => r.slot_index as number));
}

async function nextPendingQueueRow(sb: SupabaseClient, phone_slot: string): Promise<any | null> {
  const { data, error } = await sb
    .from("reels_manual_queue")
    .select("*")
    .eq("phone_slot", phone_slot)
    .eq("status", "pending")
    .order("created_at", { ascending: true })
    .limit(1)
    .maybeSingle();
  if (error) throw error;
  return data;
}

async function signedUrl(sb: SupabaseClient, path: string, ttl = 86400): Promise<string> {
  const { data, error } = await sb.storage.from(BUCKET).createSignedUrl(path, ttl);
  if (error) throw error;
  return data.signedUrl;
}

/**
 * Publish one video for (slot, slotIndex).
 * 1) Reserve the slot with a pending log row (unique index prevents dupes).
 * 2) Upload media from URL, wait for job to complete, read media id + path.
 * 3) Call publishNow; poll job; extract publer_post id + link.
 * 4) Mark queue row as posted; update publish_log to published.
 */
export async function publishOne(
  sb: SupabaseClient,
  cfg: Config,
  slot: SlotConfig,
  slotIndex: number,
  ptYmd: string,
): Promise<{ status: "published" | "no_queue" | "reserve_conflict" | "failed"; error?: string; publer_post_id?: string }> {
  const row = await nextPendingQueueRow(sb, slot.phone_slot);
  if (!row) return { status: "no_queue" };

  const planned = ptDateTimeToUtc(ptYmd, cfg.slotTimes[slotIndex]).toISOString();

  // 1) Reserve slot — unique index (phone_slot, slot_local_date, slot_index) on status in (pending,published)
  const { data: log, error: reserveErr } = await sb
    .from("publer_publish_log")
    .insert({
      queue_id: row.id,
      phone_slot: slot.phone_slot,
      slot_local_date: ptYmd,
      slot_index: slotIndex,
      planned_at: planned,
      status: "pending",
    })
    .select("id")
    .single();
  if (reserveErr) {
    if ((reserveErr as any).code === "23505") return { status: "reserve_conflict" };
    return { status: "failed", error: reserveErr.message };
  }

  // Also flip queue row to publer_publishing so it doesn't re-appear.
  await sb
    .from("reels_manual_queue")
    .update({ status: "publer_publishing" })
    .eq("id", row.id);

  try {
    // 2) Upload — serialize per workspace to respect Publer's queue rule
    const url = await signedUrl(sb, row.storage_path, 24 * 3600);
    const name = row.filename || row.storage_path.split("/").pop() || "video.mp4";
    const uploadPayload = await withUploadLock(async () => {
      const { jobId: uploadJob } = await uploadFromUrl(cfg.workspaceId, url, name);
      const payload = await waitForJob(uploadJob, {
        timeoutMs: 180_000,
        intervalMs: 3000,
        workspaceId: cfg.workspaceId,
      });
      (payload as any).__uploadJob = uploadJob;
      return payload;
    });
    const uploadJob = (uploadPayload as any).__uploadJob;

    // Payload shape from Publer for from-url upload is an array/object of media
    // { id, path, thumbnails?, ... }. Handle both array + wrapped shapes.
    let mediaObj: any = null;
    if (Array.isArray(uploadPayload)) mediaObj = uploadPayload[0];
    else if (uploadPayload?.media) {
      mediaObj = Array.isArray(uploadPayload.media) ? uploadPayload.media[0] : uploadPayload.media;
    } else if (uploadPayload?.id) mediaObj = uploadPayload;
    if (!mediaObj || !mediaObj.id) throw new Error("upload payload missing media id: " + JSON.stringify(uploadPayload).slice(0, 300));

    await sb.from("publer_publish_log").update({
      media_id: mediaObj.id,
      publer_job_id: uploadJob,
    }).eq("id", log.id);

    // 3) Publish — pull caption template + hashtag pool for this slot
    const { caption, hashtags, source: captionSource } = await composeCaption(sb, slot.phone_slot, row.id);
    console.log("[publisher] caption source:", captionSource, "for queue", row.id);
    const { jobId: publishJob } = await publishNow({
      workspaceId: cfg.workspaceId,
      accountId: slot.publer_account_id,
      provider: slot.provider,
      text: caption,
      mediaId: mediaObj.id,
      mediaPath: mediaObj.path,
      thumbnailPath: mediaObj.thumbnails?.[0]?.real,
    });

    // Record what we actually posted so analytics can correlate later
    await sb.from("publer_publish_log").update({
      caption_used: caption,
      hashtags_used: hashtags,
    }).eq("id", log.id);
    const publishPayload = await waitForJob(publishJob, {
      timeoutMs: 120_000,
      intervalMs: 2500,
      workspaceId: cfg.workspaceId,
    });

    // Failures embedded in payload
    const failures = publishPayload?.failures;
    if (failures && Object.keys(failures).length) {
      throw new Error("publer publish failures: " + JSON.stringify(failures).slice(0, 400));
    }

    // Log full payload shape once so we can build a proper post-id resolver.
    // Diagnostic only; safe to leave on — payload is small.
    console.log(
      "[publer.publish]",
      slot.phone_slot,
      "job=" + publishJob,
      "payload=" + JSON.stringify(publishPayload).slice(0, 800),
    );

    // Resolve the created post's ID and link.
    //
    // Publer's publish job payload MAY include post_ids depending on network.
    // For IG the newest-in-list heuristic worked because IG shows up in
    // /posts within seconds; for TikTok, propagation lag caused us to grab
    // an unrelated older post. Fix: only accept a listed post if it was
    // created within a small window around our job's completion AND its
    // provider matches the account we published to.
    let postId: string | undefined;
    let postLink: string | undefined;

    // 1) Preferred path: pull directly from job payload.
    const payloadPostIds: string[] | undefined =
      publishPayload?.post_ids ||
      publishPayload?.posts?.map((p: any) => p?.id).filter(Boolean);
    if (payloadPostIds && payloadPostIds.length) {
      postId = payloadPostIds[0];
    }

    // 2) Fallback: poll listPosts and match strictly on account, state,
    //    and recency (created within the last 4 minutes of now).
    if (!postId || !postLink) {
      const cutoff = Date.now() - 4 * 60_000;
      for (let i = 0; i < 6; i++) {
        await new Promise((r) => setTimeout(r, 2500));
        try {
          const listed = await listPosts(cfg.workspaceId, {
            accountId: slot.publer_account_id,
            page: 1,
          });
          const posts = (listed?.posts ?? []).filter((p: any) => {
            if (p.state !== "published") return false;
            if (!p.post_link) return false;
            // scheduled_at is when Publer marked the post; must be recent
            const at = p.scheduled_at ? Date.parse(p.scheduled_at) : NaN;
            if (isNaN(at) || at < cutoff) return false;
            // if we already have an id from the payload, use it strictly
            if (postId && p.id !== postId) return false;
            return true;
          });
          if (posts.length) {
            const p = posts[0];
            postId = postId || p.id;
            postLink = p.post_link || p.short_link || p.link;
            break;
          }
        } catch {}
      }
    }

    // If we still have no link, don't record a fake one — leave publer_post_link null.
    if (!postLink) {
      console.warn(
        "[publer.publish] could not resolve fresh post link for job",
        publishJob,
        "slot=" + slot.phone_slot,
      );
    }

    // 4) Mark posted (raw_publish_payload lets us diagnose without redeploying)
    await sb.from("publer_publish_log").update({
      publer_job_id: publishJob,
      publer_post_id: postId,
      publer_post_link: postLink,
      raw_publish_payload: publishPayload,
      status: "published",
      updated_at: new Date().toISOString(),
    }).eq("id", log.id);

    await sb.from("reels_manual_queue").update({
      status: "posted",
      posted_at: new Date().toISOString(),
      posted_ig_url: postLink,
      notes: (row.notes ? row.notes + " | " : "") + "via publer",
    }).eq("id", row.id);

    return { status: "published", publer_post_id: postId };
  } catch (e: any) {
    // Roll queue row back to pending so it can retry later, mark log failed.
    await sb.from("publer_publish_log").update({
      status: "failed",
      error: String(e.message || e).slice(0, 2000),
      updated_at: new Date().toISOString(),
    }).eq("id", log.id);
    await sb.from("reels_manual_queue").update({
      status: "pending",
    }).eq("id", row.id);
    return { status: "failed", error: String(e.message || e) };
  }
}

/**
 * One publisher tick. Called by cron every 5min.
 */
export async function publisherTick(sb: SupabaseClient): Promise<{
  attempts: Array<{ slot: string; slotIndex: number; result: string; error?: string }>;
}> {
  const cfg = await loadConfig(sb);
  const slots = await loadSlots(sb);
  const now = ptNow();
  const attempts: any[] = [];

  for (const s of slots) {
    if (s.paused) continue;
    const eligible = eligibleSlotIndexes(cfg.slotTimes, s.daily_target, now.minutes);
    const taken = await takenSlotIndexes(sb, s.phone_slot, now.ymd);
    for (const idx of eligible) {
      if (taken.has(idx)) continue;
      const r = await publishOne(sb, cfg, s, idx, now.ymd);
      attempts.push({ slot: s.phone_slot, slotIndex: idx, result: r.status, error: r.error });
      if (r.status === "no_queue" || r.status === "reserve_conflict") {
        // No point trying the next slot index if queue empty; but conflict means
        // someone else claimed idx, keep looking.
        if (r.status === "no_queue") break;
      }
      // Publish one at a time per tick per slot to avoid IG bursty behavior.
      if (r.status === "published" || r.status === "failed") break;
    }
  }
  return { attempts };
}

// --- Analytics poller --------------------------------------------------------

/**
 * Snapshot analytics for all publer_post_ids whose most recent snapshot age
 * satisfies the polling cadence:
 *   < 7 days since published:  every 30 min
 *   7-30 days:                 every hour
 *   > 30 days:                 frozen (no more snapshots)
 */
export async function analyticsTick(sb: SupabaseClient): Promise<{
  snapshots: number;
}> {
  const cfg = await loadConfig(sb);
  const slots = await loadSlots(sb);
  const now = new Date();

  // Build the map account_id -> slot for reverse-lookup
  const accountToSlot = new Map<string, SlotConfig>();
  for (const s of slots) accountToSlot.set(s.publer_account_id, s);

  // Recent post window: 30 days back from now, formatted YYYY-MM-DD in PT
  const to = ptNow(now).ymd;
  const fromDate = new Date(now.getTime() - 30 * 86400_000);
  const from = ptNow(fromDate).ymd;

  let snapshots = 0;

  for (const s of slots) {
    // Skip if account has no posts yet (we still call and it comes back empty)
    let page = 0;
    while (true) {
      const resp = await postInsights(cfg.workspaceId, s.publer_account_id, from, to, {
        page,
        sortBy: "scheduled_at",
        sortType: "DESC",
      });
      const posts = resp?.posts ?? [];
      if (!posts.length) break;

      for (const p of posts) {
        // Determine if we should snapshot based on age
        const pubAt = p.scheduled_at ? new Date(p.scheduled_at) : null;
        if (!pubAt) continue;
        const ageDays = (now.getTime() - pubAt.getTime()) / 86400_000;
        if (ageDays > 30) continue;
        const minGapMin = ageDays < 7 ? 30 : 60;

        // Publer analytics fields are nested { name, value, tooltip } objects.
        const a = p.analytics || {};
        const v = (k: string) => {
          const x = a[k];
          if (x == null) return null;
          if (typeof x === "object" && "value" in x) return x.value ?? null;
          return x;
        };

        // Join key: prefer post_link (stable across /posts + /post_insights)
        // then fall back to the internal post id.
        const joinKey = p.post_link || String(p.id);

        // Get most recent snapshot for this key
        const { data: latest2 } = await sb
          .from("publer_analytics")
          .select("captured_at")
          .eq("publer_post_id", joinKey)
          .order("captured_at", { ascending: false })
          .limit(1)
          .maybeSingle();
        const lastCap2 = latest2?.captured_at ? new Date(latest2.captured_at) : null;
        if (lastCap2 && (now.getTime() - lastCap2.getTime()) / 60000 < minGapMin) continue;

        await sb.from("publer_analytics").insert({
          publer_post_id: joinKey,
          phone_slot: s.phone_slot,
          captured_at: now.toISOString(),
          reach: v("reach"),
          engagement: v("engagement"),
          engagement_rate: v("engagement_rate"),
          likes: v("likes"),
          comments: v("comments"),
          shares: v("shares"),
          saves: v("saves"),
          video_views: v("video_views"),
          link_clicks: v("link_clicks"),
          post_clicks: v("post_clicks"),
          click_through_rate: v("click_through_rate"),
          reach_rate: v("reach_rate"),
          raw: p,
        });
        snapshots++;
      }

      if (posts.length < 10) break;
      page++;
      if (page > 20) break; // safety
    }
  }
  return { snapshots };
}

// --- Discovery convenience ---------------------------------------------------

/**
 * Reconcile our slot map with what's actually connected in Publer. Only used
 * from a manual endpoint when accounts get re-connected.
 */
export async function reconcileSlotAccounts(sb: SupabaseClient): Promise<{
  matched: number;
  unmatched: string[];
}> {
  const cfg = await loadConfig(sb);
  const publerAccounts = await listAccounts(cfg.workspaceId);
  const slots = await loadSlots(sb);
  const byId = new Map(publerAccounts.map((a) => [a.id, a] as const));
  let matched = 0;
  const unmatched: string[] = [];
  for (const s of slots) {
    const p = byId.get(s.publer_account_id);
    if (p) matched++;
    else unmatched.push(s.phone_slot);
  }
  return { matched, unmatched };
}
